test_average (__main__.TestExercice) ... ok
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... ok
test_to_degrees (__main__.TestExercice) ... ERROR
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 80, in test_to_degrees
    output = [exercice.to_degrees(v) for v in values]
  File "test_exercice.py", line 80, in <listcomp>
    output = [exercice.to_degrees(v) for v in values]
  File "/home/runner/work/2021h-ch3-exercices-phhad/2021h-ch3-exercices-phhad/exercice.py", line 27, in to_degrees
    degrees = (angle_rads * (180/math.pi()))
TypeError: 'float' object is not callable

======================================================================
FAIL: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 67, in test_to_radians
    'Mauvais calcul de degres -> radians'
AssertionError: Lists differ: [-4.966666666666667, 10.083055555555555, 360.0175, 400.91833333333335] != [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]

First differing element 0:
-4.966666666666667
-0.08668468618238503

- [-4.966666666666667, 10.083055555555555, 360.0175, 400.91833333333335]
+ [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748] : Mauvais calcul de degres -> radians

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
